[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "istanbul"
solc_version = "0.8.27"
remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
skale = "https://base-sepolia-testnet.skalenodes.com/v1/bite-v2-sandbox-2"
